# Generated by Django 6.1.1 on 2026-10-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='strat_date',
            new_name='start_date',
        ),
    ]
