# Generated by Django 6.1.1 on 2026-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_mess_customer_user'),
        ('subscriptions', '0003_subscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('customer', 'subscription_month'), name='unique_customer_subscription_month'),
        ),
    ]
