# Generated by Django 6.1.1 on 2026-10-02 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess', '0002_alter_mess_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='mess.mess')),
            ],
        ),
    ]
