# Generated by Django 6.1.1 on 2026-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
    ]
