# Generated by Django 6.1.1 on 2026-09-29 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_mess_owner'),
        ('users', '0003_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_boys', to='mess.mess')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_boy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
