# Generated by Django 6.1.1 on 2026-10-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_mess_customer_user'),
        ('deliveries', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='customers.customer')),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='deliveries.deliveryboy')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meals.meal')),
            ],
        ),
    ]
